-- #1427 (perf audit finding 4): notes/mentions (ListMentions, note.go:610) は
-- note.mentions に対する array containment ("mentions" @> ARRAY[?]::varchar[])
-- で検索するが、note.tags (IDX_note_tags, 000043) と違い GIN index が無く note
-- 全行 seq scan になっていた。テーブル肥大に比例して線形悪化するため GIN index
-- を追加して index scan 化する。
--
-- note は最大テーブルなので CONCURRENTLY で書き込みを block せずに構築する
-- (000045 の "次回 large table への index 追加では CONCURRENTLY を採用する"
-- 方針に準拠)。golang-migrate v4 の postgres driver は migration を transaction
-- 外で ExecContext するため CONCURRENTLY を直接書ける。CONCURRENTLY は単一文で
-- しか実行できない (複数文だと postgres の暗黙 transaction で失敗する) ため、
-- mentions / fileIds をそれぞれ別 migration (000054 / 000055) に分割している。
CREATE INDEX CONCURRENTLY IF NOT EXISTS "IDX_note_mentions" ON "note" USING gin ("mentions");
