-- chat_message の (fromUserId, toUserId) 複合 index 追加 (#711)。
--
-- 用途:
--   1. MarkAllReadFromUser (DM unread 一括既読化) — timeline open のたびに
--      実行される high-traffic path。WHERE "fromUserId" = ? AND "toUserId" = ?
--      で絞り込む。
--   2. ListMessagesByUser — 1-on-1 conversation の message 一覧。
--      WHERE ("fromUserId" = ? AND "toUserId" = ?) OR ("fromUserId" = ? AND
--      "toUserId" = ?) を 2 回走らせる plan を高速化 (production volume で
--      BitmapOr Scan に切り替わる plan)。
--   3. SearchMessages — text ILIKE と組み合わせた DM 検索。
--
-- 既存の単一 index "IDX_chat_message_fromUserId" は他クエリ
-- (例: ListHistory の DISTINCT ON 経路で fromUserId だけで絞るパス) で
-- 引き続き有効なので残す。複合 index と prefix で重複するが index size の
-- overhead より plan 安定性を優先する。これは upstream Misskey TS にも存在
-- する既存 index で、drop-in 互換のため touch しない。
--
-- upstream Misskey TS には複合 index は無い (本 PR で mk-go 独自に追加する
-- 最適化)。drop-in で TS DB を引き継いだ環境でも IF NOT EXISTS で安全に
-- 適用できる。逆方向 (mk-go で立てた DB を TS に戻す) も TS 側がこの index
-- を知らないだけで害なし。
--
-- 否定 array containment (NOT (reads @> ARRAY[?]::varchar[])) は GIN でも
-- 高速化できないため reads 用 index は追加しない。
--
-- 本 CREATE INDEX は ACCESS EXCLUSIVE lock を取って書き込みを一時 block
-- するが、golang-migrate v4 の postgres driver は migration を transaction
-- 外で実行する (postgres.go:296 で直接 ExecContext) ので、large table 用
-- には CREATE INDEX CONCURRENTLY を直接書ける (#754 で確認、本 migration
-- は小規模 chat_message かつ既存 production 影響を最小化したいので通常
-- 形を採用)。次回 large table への index 追加では CONCURRENTLY を採用する。
CREATE INDEX IF NOT EXISTS "IDX_chat_message_fromUserId_toUserId"
    ON "chat_message" ("fromUserId", "toUserId");
