-- data loss: 生成済みの秘密値が失われる。
--
-- **テーブルごと消えるので、この状態では mk-go が起動しない。** GetOrCreate は
-- テーブル不在 (42P01) を gorm.ErrRecordNotFound として扱わないため生成の分岐に
-- 入らず、resolveMediaProxySecret -> server.New が失敗して os.Exit(1) する。
-- default.yml.example は mediaProxySecret をコメントアウトしているので、既定構成の
-- 運用者は全員これに当たる。設定ファイルに mediaProxySecret を書いていれば回避できる。
--
-- 鍵だけを入れ替える (行を消してテーブルは残す) 場合は、発行済みの署名付き URL が
-- 検証に失敗するが、Authorize は allowlist へフォールバックするので avatar / drive /
-- emoji / instance icon の配信は継続する。allowlist に載らず署名だけで通していた
-- URL (role icon / announcement image 等) は 401 になる。
DROP TABLE IF EXISTS "instance_secret";
