// Package pluginspec extracts the exported surface of the plugin/ package.
//
// plugin/ は公開した時点から semver の義務を負う。export を足すのは意図的な
// 判断であるべきなので、golden の差分としてレビューに出す (#2478)。手で一覧を
// 維持すると実装とずれるため、出力元はコードにする。
package pluginspec

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/printer"
	"go/token"
	"io"
	"os"
	"sort"
	"strings"
)

// DefaultDir is the package whose surface is tracked.
const DefaultDir = "plugin"

// DefaultGolden is where the snapshot lives.
const DefaultGolden = "internal/entitycompat/testdata/golden_plugin_surface.txt"

// Surface returns the sorted list of exported identifiers in the package.
//
// 形まで含めて記録する (関数のシグネチャ、interface のメソッド)。名前だけだと
// 「引数が 1 つ増えた」ような破壊的変更を検出できない。
func Surface(dir string) ([]string, error) {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, func(fi os.FileInfo) bool {
		return !strings.HasSuffix(fi.Name(), "_test.go")
	}, 0)
	if err != nil {
		return nil, fmt.Errorf("%s を解析できません: %w", dir, err)
	}

	var out []string
	for _, pkg := range pkgs {
		for _, file := range pkg.Files {
			for _, decl := range file.Decls {
				out = append(out, declEntries(fset, decl)...)
			}
		}
	}
	sort.Strings(out)
	return out, nil
}

// declEntries renders one top-level declaration's exported entries.
func declEntries(fset *token.FileSet, decl ast.Decl) []string {
	switch d := decl.(type) {
	case *ast.FuncDecl:
		if !d.Name.IsExported() {
			return nil
		}
		recv := ""
		if d.Recv != nil && len(d.Recv.List) > 0 {
			// 非公開型のメソッドは公開面ではない。
			t := typeString(fset, d.Recv.List[0].Type)
			if !isExportedType(t) {
				return nil
			}
			recv = "(" + t + ") "
		}
		return []string{"func " + recv + d.Name.Name + signature(fset, d.Type)}

	case *ast.GenDecl:
		var out []string
		for _, spec := range d.Specs {
			out = append(out, specEntries(fset, d.Tok, spec)...)
		}
		return out
	}
	return nil
}

// specEntries renders type / const / var specs.
func specEntries(fset *token.FileSet, tok token.Token, spec ast.Spec) []string {
	switch s := spec.(type) {
	case *ast.TypeSpec:
		if !s.Name.IsExported() {
			return nil
		}
		out := []string{"type " + s.Name.Name + " " + kindOf(s.Type)}
		// interface と struct は中身まで記録する。メソッドが 1 つ増えるのは
		// 実装側にとって破壊的変更なので、名前だけでは足りない。
		switch t := s.Type.(type) {
		case *ast.InterfaceType:
			for _, m := range t.Methods.List {
				for _, name := range m.Names {
					if !name.IsExported() {
						continue
					}
					if ft, ok := m.Type.(*ast.FuncType); ok {
						out = append(out, "  method "+s.Name.Name+"."+name.Name+signature(fset, ft))
					}
				}
			}
		case *ast.StructType:
			for _, f := range t.Fields.List {
				for _, name := range f.Names {
					if !name.IsExported() {
						continue
					}
					out = append(out, "  field "+s.Name.Name+"."+name.Name+" "+typeString(fset, f.Type))
				}
			}
		}
		return out

	case *ast.ValueSpec:
		var out []string
		for _, name := range s.Names {
			if !name.IsExported() {
				continue
			}
			out = append(out, tok.String()+" "+name.Name)
		}
		return out
	}
	return nil
}

// kindOf labels the underlying kind of a type spec.
func kindOf(expr ast.Expr) string {
	switch expr.(type) {
	case *ast.InterfaceType:
		return "interface"
	case *ast.StructType:
		return "struct"
	case *ast.FuncType:
		return "func"
	default:
		return "other"
	}
}

// signature renders a function signature without parameter names, so renaming a
// parameter does not show up as a surface change.
func signature(fset *token.FileSet, ft *ast.FuncType) string {
	params := fieldTypes(fset, ft.Params)
	results := fieldTypes(fset, ft.Results)
	sig := "(" + strings.Join(params, ", ") + ")"
	switch len(results) {
	case 0:
	case 1:
		sig += " " + results[0]
	default:
		sig += " (" + strings.Join(results, ", ") + ")"
	}
	return sig
}

// fieldTypes lists the types in a parameter or result list, expanding grouped
// names (`a, b string` → two entries).
func fieldTypes(fset *token.FileSet, fl *ast.FieldList) []string {
	if fl == nil {
		return nil
	}
	var out []string
	for _, f := range fl.List {
		t := typeString(fset, f.Type)
		n := len(f.Names)
		if n == 0 {
			n = 1
		}
		for i := 0; i < n; i++ {
			out = append(out, t)
		}
	}
	return out
}

// typeString renders a type expression.
func typeString(fset *token.FileSet, expr ast.Expr) string {
	var b strings.Builder
	if err := printExpr(&b, fset, expr); err != nil {
		return "?"
	}
	return b.String()
}

// printExpr writes the source form of a type expression.
func printExpr(w io.Writer, fset *token.FileSet, expr ast.Expr) error {
	return printer.Fprint(w, fset, expr)
}

// Render formats the surface for the golden file.
func Render(surface []string) string {
	var b strings.Builder
	b.WriteString("# Code generated by tools/pluginspec. DO NOT EDIT.\n")
	b.WriteString("# plugin/ の公開面。差分はレビューで意図を確認すること (#2478)。\n")
	for _, s := range surface {
		b.WriteString(s + "\n")
	}
	return b.String()
}

// isExportedType reports whether a receiver type string names an exported type.
func isExportedType(s string) bool {
	s = strings.TrimPrefix(s, "*")
	if s == "" {
		return false
	}
	return s[0] >= 'A' && s[0] <= 'Z'
}
