package entitycompat

import (
	_ "embed"
	"encoding/json"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"
)

// embeddedErrorKindsJSON is the committed golden of Misskey's EXPLICIT per-error
// `kind` discriminators (endpoint -> code -> kind), generated by
// `go run ./tools/erroriddiff`. It holds only errors where Misskey writes a
// kind in the error definition; the implicit-client majority is intentionally
// absent and is gated via golden_error_ids membership instead (see below).
//
//go:embed testdata/golden_error_kinds.json
var embeddedErrorKindsJSON []byte

// TestErrorKindDrift gates the `kind` discriminator of error envelopes
// (#1608). upstream ApiCallService.send() always serializes `kind`
// (ApiError defaults to 'client'), and `#sendApiError` derives the
// WWW-Authenticate header from it, so an emission whose kind differs from
// upstream changes both the body shape and the auth-challenge header.
//
// Two directions are gated for every confidently-resolved emission:
//   - the golden kinds snapshot has an explicit kind for (endpoint, code):
//     the emission must match it (e.g. NO_SUCH_ABUSE_REPORT is 'server').
//   - otherwise, when the id golden shows upstream defines that code for the
//     endpoint, the emission must carry the default 'client'. Codes unknown
//     to upstream (mk-go-specific) are not gated.
func TestErrorKindDrift(t *testing.T) {
	root := repoRoot(t)

	var goldenKinds map[string]map[string]string
	if err := json.Unmarshal(embeddedErrorKindsJSON, &goldenKinds); err != nil {
		t.Fatalf("parse golden_error_kinds.json: %v", err)
	}
	// 明示 kind は少数 (upstream 全体で数件) なので >=5 程度を健全性下限とする。
	if len(goldenKinds) < 5 {
		t.Fatalf("kind golden has only %d endpoints (expected >=5); regenerate with `make shapecheck-gen`", len(goldenKinds))
	}
	var goldenIDs map[string]map[string]string
	if err := json.Unmarshal(embeddedErrorIDsJSON, &goldenIDs); err != nil {
		t.Fatalf("parse golden_error_ids.json: %v", err)
	}

	routes := parseRoutes(t, filepath.Join(root, "internal/server/router.go"))
	helpers, consts := parseApierr(t, filepath.Join(root, "internal/api/apierr/errors.go"))
	for name, em := range parseJSONWrappers(t, filepath.Join(root, "internal/api/apierr/echo.go"), helpers) {
		helpers[name] = em
	}

	type drift struct{ endpoint, code, got, want string }
	var drifts []drift
	resolved := 0

	apiDir := filepath.Join(root, "internal/api")
	err := filepath.WalkDir(apiDir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() || !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
			return nil
		}
		pkg := filepath.Base(filepath.Dir(path))
		src, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		for _, em := range scanEmissions(string(src), helpers, consts) {
			for _, route := range routes[pkg+"\x00"+em.fn] {
				resolved++
				ep := strings.TrimPrefix(route, "/")
				if excludedEndpoint(ep) {
					continue
				}
				want, explicit := goldenKinds[ep][em.code]
				if !explicit {
					// upstream がこの endpoint で code を定義していなければ
					// mk-go 固有 code: gate 対象外。定義していて kind が
					// 無いものは ApiError default の client を要求する。
					if _, defined := goldenIDs[ep][em.code]; !defined {
						continue
					}
					want = "client"
				}
				if em.kind != want {
					drifts = append(drifts, drift{ep, em.code, em.kind, want})
				}
			}
		}
		return nil
	})
	if err != nil {
		t.Fatalf("walk api dir: %v", err)
	}

	// silent-zero guard: scanner / route 解決が空振りすると gate が vacuous PASS
	// するため、error-id gate と同じ下限で parser 破損を検出する。
	if resolved < 400 {
		t.Fatalf("kind gate resolved only %d emissions (expected >=400); the source/router parser likely broke", resolved)
	}

	if len(drifts) > 0 {
		sort.Slice(drifts, func(i, j int) bool {
			if drifts[i].endpoint != drifts[j].endpoint {
				return drifts[i].endpoint < drifts[j].endpoint
			}
			return drifts[i].code < drifts[j].code
		})
		var b strings.Builder
		b.WriteString("error kind drift: handler emits a kind that differs from Misskey's per-endpoint kind.\n")
		b.WriteString("Use apierr.ErrorWithKind (or the matching helper) to align with the upstream kind.\n")
		for _, d := range drifts {
			b.WriteString("  " + d.endpoint + " " + d.code + ": got " + d.got + " want " + d.want + "\n")
		}
		t.Fatal(b.String())
	}
}
