package entitycompat

import (
	_ "embed"
	"encoding/json"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"testing"
)

// embeddedErrorStatusJSON is the committed golden of Misskey's EXPLICIT per-error
// HTTP statuses (endpoint -> code -> status), generated by `go run ./tools/erroriddiff`.
// It holds only errors where Misskey sets httpStatusCode or a non-default kind;
// the implicit-400 majority is intentionally absent (see below).
//
//go:embed testdata/golden_error_status.json
var embeddedErrorStatusJSON []byte

// httpStatusValue maps the net/http status constant names used in handler code
// to their numeric value, so emitted statuses can be compared against the golden.
var httpStatusValue = map[string]int{
	"StatusOK":                    200,
	"StatusNoContent":             204,
	"StatusBadRequest":            400,
	"StatusUnauthorized":          401,
	"StatusForbidden":             403,
	"StatusNotFound":              404,
	"StatusConflict":              409,
	"StatusGone":                  410,
	"StatusRequestEntityTooLarge": 413,
	"StatusUnprocessableEntity":   422,
	"StatusTooManyRequests":       429,
	"StatusInternalServerError":   500,
	"StatusBadGateway":            502,
	"StatusServiceUnavailable":    503,
}

// TestErrorHTTPStatusDrift gates the HTTP status of error responses, but ONLY
// for the errors where Misskey explicitly pins a status (httpStatusCode or a
// non-default kind). Misskey returns 400 for ~95% of errors by default (kind
// defaults to 'client'); mk-go intentionally keeps semantic statuses (404 for
// NO_SUCH_*, 403 for ACCESS_DENIED) for those, and misskey-js does not branch on
// the specific status. So only the explicit-status set is contractually binding,
// and that is what this gate enforces.
func TestErrorHTTPStatusDrift(t *testing.T) {
	root := repoRoot(t)

	var golden map[string]map[string]int
	if err := json.Unmarshal(embeddedErrorStatusJSON, &golden); err != nil {
		t.Fatalf("parse golden_error_status.json: %v", err)
	}
	if len(golden) < 5 {
		t.Fatalf("status golden has only %d endpoints (expected >=5); regenerate with `make shapecheck-gen`", len(golden))
	}

	routes := parseRoutes(t, filepath.Join(root, "internal/server/router.go"))
	helpers, _ := parseApierr(t, filepath.Join(root, "internal/api/apierr/errors.go"))
	wrappers := parseJSONWrapperStatuses(t, filepath.Join(root, "internal/api/apierr/echo.go"), helpers)

	// mkStatus collects mk-go's emitted status per (endpoint, code).
	mkStatus := map[string]map[string]int{}
	resolved := 0
	record := func(pkg, fn, code string, status int) {
		for _, route := range routes[pkg+"\x00"+fn] {
			resolved++
			ep := strings.TrimPrefix(route, "/")
			if mkStatus[ep] == nil {
				mkStatus[ep] = map[string]int{}
			}
			mkStatus[ep][code] = status
		}
	}

	apiDir := filepath.Join(root, "internal/api")
	err := filepath.WalkDir(apiDir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() || !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
			return nil
		}
		pkg := filepath.Base(filepath.Dir(path))
		src, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		for _, em := range scanStatusEmissions(string(src), helpers, wrappers) {
			record(pkg, em.fn, em.code, em.status)
		}
		return nil
	})
	if err != nil {
		t.Fatalf("walk api dir: %v", err)
	}

	// silent-zero guard: scanStatusEmissions / route 解決が空振りすると mkStatus
	// が空になり、golden の各 entry が「未 emit」で skip され gate が vacuous PASS
	// する。実際の解決数は数百あるので、大きく下回ったら parser 破損とみなす。
	if resolved < 300 {
		t.Fatalf("status gate resolved only %d emissions (expected >=300); the source/router parser likely broke", resolved)
	}

	type drift struct {
		endpoint, code string
		got, want      int
	}
	var drifts []drift
	for ep, codes := range golden {
		if excludedEndpoint(ep) {
			continue
		}
		for code, want := range codes {
			got, ok := mkStatus[ep][code]
			if !ok {
				continue // route not resolved or code not emitted: not gated
			}
			if got != want {
				drifts = append(drifts, drift{ep, code, got, want})
			}
		}
	}

	if len(drifts) > 0 {
		sort.Slice(drifts, func(i, j int) bool {
			if drifts[i].endpoint != drifts[j].endpoint {
				return drifts[i].endpoint < drifts[j].endpoint
			}
			return drifts[i].code < drifts[j].code
		})
		var b strings.Builder
		b.WriteString("error HTTP status drift: handler emits a status differing from Misskey's explicit status.\n")
		for _, d := range drifts {
			b.WriteString(formatStatusDrift(d.endpoint, d.code, d.got, d.want))
		}
		t.Fatal(b.String())
	}
}

func formatStatusDrift(ep, code string, got, want int) string {
	return "  " + ep + " " + code + ": got " + itoa(got) + " want " + itoa(want) + "\n"
}

func itoa(n int) string {
	if n == 0 {
		return "?"
	}
	var b []byte
	for n > 0 {
		b = append([]byte{byte('0' + n%10)}, b...)
		n /= 10
	}
	return string(b)
}

type statusEmission struct {
	fn     string
	code   string
	status int
}

var (
	// inlineStatusErrRe matches c.JSON(http.StatusX, apierr.Error("CODE", ...)).
	inlineStatusErrRe = regexp.MustCompile(`c\.JSON\(http\.(\w+),\s*apierr\.Error\("([A-Z_]+)"`)
	// inlineStatusHelperRe matches c.JSON(http.StatusX, apierr.Helper()).
	inlineStatusHelperRe = regexp.MustCompile(`c\.JSON\(http\.(\w+),\s*apierr\.(\w+)\(\)`)
	// wrapperCallRe matches apierr.JSONXxx(c) wrapper calls.
	wrapperCallRe = regexp.MustCompile(`apierr\.(JSON\w+)\(c\)`)
)

// scanStatusEmissions extracts (method, code, status) triples from a handler
// file: inline c.JSON(status, Error/Helper) and JSONXxx(c) wrapper calls.
func scanStatusEmissions(src string, helpers, wrappers map[string]emission) []statusEmission {
	locs := funcDeclRe.FindAllStringSubmatchIndex(src, -1)
	var out []statusEmission
	for i, loc := range locs {
		fn := src[loc[2]:loc[3]]
		end := len(src)
		if i+1 < len(locs) {
			end = locs[i+1][0]
		}
		body := src[loc[0]:end]

		for _, m := range inlineStatusErrRe.FindAllStringSubmatch(body, -1) {
			if st, ok := httpStatusValue[m[1]]; ok {
				out = append(out, statusEmission{fn: fn, code: m[2], status: st})
			}
		}
		for _, m := range inlineStatusHelperRe.FindAllStringSubmatch(body, -1) {
			if h, ok := helpers[m[2]]; ok {
				if st, ok := httpStatusValue[m[1]]; ok {
					out = append(out, statusEmission{fn: fn, code: h.code, status: st})
				}
			}
		}
		for _, m := range wrapperCallRe.FindAllStringSubmatch(body, -1) {
			if w, ok := wrappers[m[1]]; ok {
				out = append(out, statusEmission{fn: fn, code: w.code, status: w.status})
			}
		}
	}
	return out
}

var jsonWrapperStatusRe = regexp.MustCompile(`c\.JSON\(http\.(\w+),\s*(\w+)\(`)

// parseJSONWrapperStatuses reads echo.go and returns JSONXxx -> {code, status}
// by resolving the wrapper's inner helper call (for the code) and its c.JSON
// status argument.
func parseJSONWrapperStatuses(t *testing.T, path string, helpers map[string]emission) map[string]emission {
	src, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read echo wrappers: %v", err)
	}
	out := map[string]emission{}
	locs := jsonWrapperRe.FindAllStringSubmatchIndex(string(src), -1)
	for i, loc := range locs {
		name := string(src[loc[2]:loc[3]])
		end := len(src)
		if i+1 < len(locs) {
			end = locs[i+1][0]
		}
		if m := jsonWrapperStatusRe.FindStringSubmatch(string(src[loc[0]:end])); m != nil {
			if h, ok := helpers[m[2]]; ok {
				out[name] = emission{code: h.code, status: httpStatusValue[m[1]]}
			}
		}
	}
	return out
}
