package entitycompat

import (
	_ "embed"
	"encoding/json"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"testing"
)

// embeddedLimitSpecsJSON is the committed golden of Misskey's per-endpoint
// pagination limit paramDef (endpoint -> {default, max}), generated by
// `go run ./tools/limitspec`.
//
//go:embed testdata/golden_limit_specs.json
var embeddedLimitSpecsJSON []byte

type limitSpec struct {
	Default int `json:"default"`
	Max     int `json:"max"`
}

// clampLimitRe matches pagination.ClampLimit(<limit>, <def>, <max>) and captures
// the def / max integer literals.
var clampLimitRe = regexp.MustCompile(`pagination\.ClampLimit\([^,]+,\s*(\d+)\s*,\s*(\d+)\s*\)`)

// TestLimitSpecDrift is the pagination limit gate. Handlers normalize their
// page-size limit via pagination.ClampLimit(limit, def, max); this test reads
// the def / max literals at each call site, resolves the enclosing method to
// its route, and checks them against Misskey's paramDef (default / maximum).
//
// Coverage grows as handlers migrate to ClampLimit (like the L3 expansion):
// only call sites that resolve to an endpoint with a golden spec are gated, so
// not-yet-migrated handlers are simply unchecked rather than failing.
func TestLimitSpecDrift(t *testing.T) {
	root := repoRoot(t)

	var golden map[string]limitSpec
	if err := json.Unmarshal(embeddedLimitSpecsJSON, &golden); err != nil {
		t.Fatalf("parse golden_limit_specs.json: %v", err)
	}
	if len(golden) < 50 {
		t.Fatalf("limit golden has only %d endpoints (expected >=50); regenerate with `make shapecheck-gen`", len(golden))
	}

	routes := parseRoutes(t, filepath.Join(root, "internal/server/router.go"))

	type drift struct {
		endpoint  string
		field     string
		got, want int
	}
	var drifts []drift
	checked := 0

	apiDir := filepath.Join(root, "internal/api")
	err := filepath.WalkDir(apiDir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() || !strings.HasSuffix(path, ".go") || strings.HasSuffix(path, "_test.go") {
			return nil
		}
		pkg := filepath.Base(filepath.Dir(path))
		src, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		s := string(src)
		locs := funcDeclRe.FindAllStringSubmatchIndex(s, -1)
		for i, loc := range locs {
			fn := s[loc[2]:loc[3]]
			end := len(s)
			if i+1 < len(locs) {
				end = locs[i+1][0]
			}
			for _, m := range clampLimitRe.FindAllStringSubmatch(s[loc[0]:end], -1) {
				def, _ := strconv.Atoi(m[1])
				max, _ := strconv.Atoi(m[2])
				for _, route := range routes[pkg+"\x00"+fn] {
					ep := strings.TrimPrefix(route, "/")
					spec, ok := golden[ep]
					if !ok {
						continue
					}
					checked++
					if spec.Default != 0 && def != spec.Default {
						drifts = append(drifts, drift{ep, "default", def, spec.Default})
					}
					if spec.Max != 0 && max != spec.Max {
						drifts = append(drifts, drift{ep, "max", max, spec.Max})
					}
				}
			}
		}
		return nil
	})
	if err != nil {
		t.Fatalf("walk api dir: %v", err)
	}

	if checked == 0 {
		t.Fatal("limit gate resolved 0 ClampLimit call sites; the parser likely broke")
	}

	if len(drifts) > 0 {
		sort.Slice(drifts, func(i, j int) bool {
			if drifts[i].endpoint != drifts[j].endpoint {
				return drifts[i].endpoint < drifts[j].endpoint
			}
			return drifts[i].field < drifts[j].field
		})
		var b strings.Builder
		b.WriteString("pagination limit drift: ClampLimit literal differs from Misskey paramDef.\n")
		for _, d := range drifts {
			b.WriteString("  " + d.endpoint + " " + d.field + ": got " + strconv.Itoa(d.got) + " want " + strconv.Itoa(d.want) + "\n")
		}
		t.Fatal(b.String())
	}
}
