package entitycompat

import (
	_ "embed"
	"encoding/json"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"testing"
)

// embeddedOAuthKindsJSON is the committed golden map of Misskey endpoint ->
// meta.kind (the OAuth scope an app token must hold), generated by
// `go run ./tools/permspec`.
//
//go:embed testdata/golden_oauth_kinds.json
var embeddedOAuthKindsJSON []byte

// requireScopeRe extracts the scope string from middleware.RequireScope("...").
var requireScopeRe = regexp.MustCompile(`RequireScope\("([^"]+)"\)`)

// kindMissingScope lists endpoints where Misskey declares meta.kind but mk-go's
// route has no RequireScope, so an app token can drive them without holding the
// scope. **These are pre-existing gaps, not intentional divergence** — the gate
// exists to stop new ones while these are worked off separately.
//
// 値は「upstream が要求する kind」。潰したらこの表から消す。
// **現在は空 = 全件 upstream の kind どおりに RequireScope が付いている。**
var kindMissingScope = map[string]string{}

// TestOAuthKindDrift checks that mk-go's middleware.RequireScope matches
// Misskey's meta.kind for every endpoint both sides implement.
//
// TestPermissionDrift only compares the coarse public|auth|moderator|admin
// ladder, so a wrong OAuth scope slips through it entirely. That is not
// hypothetical: `admin/queue/stats` shipped with `read:admin:emoji` (copied from
// upstream's own typo, fixed upstream in 2026.9.0) and nothing caught it — an
// app holding only the emoji scope could read queue stats, while an app holding
// the queue scope could not.
func TestOAuthKindDrift(t *testing.T) {
	root := repoRoot(t)

	var golden map[string]string
	if err := json.Unmarshal(embeddedOAuthKindsJSON, &golden); err != nil {
		t.Fatalf("parse golden_oauth_kinds.json: %v", err)
	}
	// 拾えなくなったら落とす。upstream の書式が変わって空になると、
	// 検査していないのに緑になる。
	if len(golden) < 200 {
		t.Fatalf("oauth kinds golden has only %d entries (expected >=200); regenerate with `make shapecheck-gen`", len(golden))
	}

	regs := parseRouteRegistrations(t, filepath.Join(root, "internal/server/router.go"))
	if len(regs) < 200 {
		t.Fatalf("parsed only %d routes from router.go (expected >=200); the parser likely broke", len(regs))
	}

	var mismatched, missing, staleAllow []string
	for ep, want := range golden {
		if excludedEndpoint(ep) {
			continue
		}
		reg, ok := regs[ep]
		if !ok {
			continue // not implemented
		}
		m := requireScopeRe.FindStringSubmatch(reg)
		if m == nil {
			if _, allowed := kindMissingScope[ep]; !allowed {
				missing = append(missing, ep+" (upstream kind: "+want+")")
			}
			continue
		}
		if _, allowed := kindMissingScope[ep]; allowed {
			staleAllow = append(staleAllow, ep)
		}
		if m[1] != want {
			mismatched = append(mismatched, ep+": misskey="+want+" mk="+m[1])
		}
	}

	fail := func(head string, list []string) {
		sort.Strings(list)
		var b strings.Builder
		b.WriteString(head + "\n")
		for _, l := range list {
			b.WriteString("  " + l + "\n")
		}
		t.Error(b.String())
	}
	if len(mismatched) > 0 {
		fail("oauth kind drift: mk-go's RequireScope does not match Misskey's meta.kind.", mismatched)
	}
	if len(missing) > 0 {
		fail("oauth kind drift: Misskey declares meta.kind but mk-go's route has no RequireScope (app token bypasses the scope).\nFix the route, or register it in kindMissingScope with the upstream kind.", missing)
	}
	// allowlist が実態より広いと、直したものを検出し続けたうえで新しい欠落を隠す。
	if len(staleAllow) > 0 {
		fail("kindMissingScope is stale: these endpoints now have RequireScope. Remove them from the allowlist.", staleAllow)
	}
}
