package entitycompat

import (
	_ "embed"
	"encoding/json"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"testing"
)

// embeddedPermissionsJSON is the committed golden of Misskey's per-endpoint
// access level (endpoint -> public|auth|moderator|admin), generated by
// `go run ./tools/permspec`.
//
//go:embed testdata/golden_permissions.json
var embeddedPermissionsJSON []byte

// permRank orders access levels so the gate can compare "looser vs stricter".
// rolepolicy requires credential (and a policy) so it ranks at the auth level
// for the looseness check; moderator/admin are the privileged tiers.
var permRank = map[string]int{"public": 0, "auth": 1, "rolepolicy": 1, "moderator": 2, "admin": 3}

// routeRegRe finds the start of a router registration: api.METHOD("/path".
var routeRegRe = regexp.MustCompile(`\bapi\.(?:GET|POST|PUT|DELETE)\("(/[^"]*)"`)

// TestPermissionDrift is the access-control gate. It checks that mk-go's router
// middleware is never LOOSER than Misskey's declared per-endpoint requirement
// (requireAdmin / requireModerator / requireCredential). A looser route is a
// privilege-escalation or missing-auth bug (e.g. a moderator reaching an
// admin-only endpoint, or an anonymous request reaching a credential-required
// one).
//
// Only the looser direction is gated: mk-go being STRICTER than Misskey
// (requiring a role policy where Misskey only requires login, or requiring auth
// on a public endpoint) is a defensible hardening choice, not a security bug,
// so it is not flagged.
func TestPermissionDrift(t *testing.T) {
	root := repoRoot(t)

	var golden map[string]string
	if err := json.Unmarshal(embeddedPermissionsJSON, &golden); err != nil {
		t.Fatalf("parse golden_permissions.json: %v", err)
	}
	if len(golden) < 200 {
		t.Fatalf("permissions golden has only %d endpoints (expected >=200); regenerate with `make shapecheck-gen`", len(golden))
	}

	mk := parseRouteLevels(t, filepath.Join(root, "internal/server/router.go"))
	if len(mk) < 200 {
		t.Fatalf("parsed only %d routes from router.go (expected >=200); the parser likely broke", len(mk))
	}

	type drift struct{ endpoint, misskey, mkLevel string }
	var drifts []drift
	for ep, msLevel := range golden {
		if excludedEndpoint(ep) {
			continue
		}
		mkLevel, ok := mk[ep]
		if !ok {
			continue // not implemented / not resolved
		}
		if permRank[mkLevel] < permRank[msLevel] {
			drifts = append(drifts, drift{ep, msLevel, mkLevel})
		}
	}

	if len(drifts) > 0 {
		sort.Slice(drifts, func(i, j int) bool { return drifts[i].endpoint < drifts[j].endpoint })
		var b strings.Builder
		b.WriteString("permission drift: mk-go router is LOOSER than Misskey's required level (privilege escalation / missing auth).\n")
		for _, d := range drifts {
			b.WriteString("  " + d.endpoint + ": misskey=" + d.misskey + " mk=" + d.mkLevel + "\n")
		}
		t.Fatal(b.String())
	}
}

// parseRouteLevels reads router.go and returns endpoint path -> access level by
// balancing parentheses from each api.METHOD("/path" to the end of the
// registration call, so middleware on the closing line of a multi-line inline
// handler (}, middleware.RequireAuth())) is captured too.
func parseRouteLevels(t *testing.T, path string) map[string]string {
	src, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read router: %v", err)
	}
	s := string(src)
	levels := map[string]string{}
	for _, loc := range routeRegRe.FindAllStringSubmatchIndex(s, -1) {
		ep := strings.TrimPrefix(s[loc[2]:loc[3]], "/")
		// Balance parens from the opening '(' of api.METHOD( to its match.
		open := strings.LastIndex(s[loc[0]:loc[1]], "(") + loc[0]
		depth, j := 1, open+1
		for j < len(s) && depth > 0 {
			switch s[j] {
			case '(':
				depth++
			case ')':
				depth--
			}
			j++
		}
		reg := s[open:j]
		switch {
		case strings.Contains(reg, "RequireAdmin"):
			levels[ep] = "admin"
		case strings.Contains(reg, "RequireModerator"):
			levels[ep] = "moderator"
		case strings.Contains(reg, "RequireRolePolicy"):
			levels[ep] = "rolepolicy"
		case strings.Contains(reg, "RequireAuth"):
			levels[ep] = "auth"
		default:
			levels[ep] = "public"
		}
	}
	return levels
}
