package entitycompat

import (
	_ "embed"
	"encoding/json"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"
)

// embeddedSecureEndpointsJSON is the committed golden list of Misskey endpoints
// marked `secure: true`, generated by `go run ./tools/securespec`.
//
//go:embed testdata/golden_secure_endpoints.json
var embeddedSecureEndpointsJSON []byte

// TestSecureDrift checks that every Misskey `secure: true` endpoint that mk-go
// implements applies middleware.RequireSecure on its route. Misskey's secure
// endpoints (password / 2FA / data export-import / authorized-apps) are
// reachable only via the native session token; without RequireSecure a
// third-party OAuth app holding a valid access token could drive them.
func TestSecureDrift(t *testing.T) {
	root := repoRoot(t)

	var golden []string
	if err := json.Unmarshal(embeddedSecureEndpointsJSON, &golden); err != nil {
		t.Fatalf("parse golden_secure_endpoints.json: %v", err)
	}
	if len(golden) < 30 {
		t.Fatalf("secure golden has only %d endpoints (expected >=30); regenerate with `make shapecheck-gen`", len(golden))
	}
	secure := make(map[string]bool, len(golden))
	for _, ep := range golden {
		secure[ep] = true
	}

	regs := parseRouteRegistrations(t, filepath.Join(root, "internal/server/router.go"))

	var missing []string
	for ep, reg := range regs {
		if !secure[ep] || excludedEndpoint(ep) {
			continue
		}
		if !strings.Contains(reg, "RequireSecure") {
			missing = append(missing, ep)
		}
	}

	if len(missing) > 0 {
		sort.Strings(missing)
		var b strings.Builder
		b.WriteString("secure drift: Misskey `secure: true` endpoint lacks middleware.RequireSecure (app token could drive it).\n")
		for _, ep := range missing {
			b.WriteString("  " + ep + "\n")
		}
		t.Fatal(b.String())
	}
}

// parseRouteRegistrations returns endpoint path -> the full router registration
// text (balanced parens), so middleware on a multi-line inline handler's closing
// line is included.
func parseRouteRegistrations(t *testing.T, path string) map[string]string {
	src, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read router: %v", err)
	}
	s := string(src)
	out := map[string]string{}
	for _, loc := range routeRegRe.FindAllStringSubmatchIndex(s, -1) {
		ep := strings.TrimPrefix(s[loc[2]:loc[3]], "/")
		open := strings.LastIndex(s[loc[0]:loc[1]], "(") + loc[0]
		depth, j := 1, open+1
		for j < len(s) && depth > 0 {
			switch s[j] {
			case '(':
				depth++
			case ')':
				depth--
			}
			j++
		}
		out[ep] = s[open:j]
	}
	return out
}
